# Generated by Django 2.2.7 on 2019-12-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(default='', max_length=100)),
                ('Total_Marks', models.CharField(default='', max_length=100)),
                ('Marks_Scored', models.CharField(default='', max_length=100)),
                ('Status', models.CharField(default='', max_length=10)),
                ('PhoneNumber', models.CharField(default=1, max_length=12)),
                ('unique_id', models.IntegerField()),
                ('First_Round_Interviewer_Name', models.CharField(default='', max_length=100)),
                ('Second_Round_Interviewer_Name', models.CharField(default='', max_length=100)),
                ('Third_Round_Interviewer_Name', models.CharField(default='', max_length=100)),
                ('Management_Round_Interviewer_Name', models.CharField(default='', max_length=100)),
                ('HR_Round_Interviewer_Name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('DateOfDrive', models.DateField(default='2019-01-01')),
                ('NameOfDrive', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('DateOfDrive', 'NameOfDrive')},
            },
        ),
    ]
