# Generated by Django 2.2.7 on 2019-12-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
